import { ArrowRight } from "lucide-react";
import React, { useContext } from "react";
import { DarkModeContext } from "../../Contexts/DarkModeContext";

const HomeSectionbottom = () => {
  const {Darkmode} = useContext(DarkModeContext)

  return (
    <section className={` flex lg:flex-row flex-col items-center  lg:px-28 md:px-16 px-10 py-6 md:gap-6 ${Darkmode ? " bg-dark_gray-900 text-white":" bg-slate-100"}`}>
      <div className=" lg:w-1/2">
        <img src="./Img/Landing-5.webp" alt="bOATH" />
      </div>
      <div className=" lg:w-1/2">
        <h2 className="title text-4xl font-bold my-6">
          What is bOATH?
        </h2>
        <div className=" grid grid-cols-1 gap-5">
          <p>
            Bonded OATH (bOATH) is 20% ETH and 80% OATH, backed by a
            Balancer-powered 80/20 liquidity pool. bOATH earns platform fees and
            benefits from trading fees generated by Ethos&apos;s incentive buyback and
            distribution strategies.
            A $bOATH position staked on Ethos will earn
            yield from ERN loan issuance fees, and redemption rewards.
          </p>
        </div>
        <a
          href="#"
          className="navigate_anchor flex gap-2 w-fit my-3 transition p-2 rounded hover:bg-slate-200 hover:text-purple-600 font-semibold"
        >
          <ArrowRight className="icon h-full" />
          Get bOATH Tokens
        </a>
      </div>
    </section>
  );
};

export default HomeSectionbottom;
