import React, { useContext } from 'react'
import { DarkModeContext } from '../../Contexts/DarkModeContext';

const DashboardTerms = ({showTerm, setshowTerm}) => {
    const { Darkmode } = useContext(DarkModeContext);

  return (
    <div
      className={` ${
        showTerm ? "flex " : "hidden" 
      } h-screen w-screen items-center justify-center fixed top-0 left-0 z-50`}
    >
      <div className={` ${Darkmode?" bg-dark_gray-900 text-white":" bg-white"} h-[90vh] rounded-xl min-w-[350px] w-[60vw]  p-4 flex flex-col items-center justify-center`}>
        <h3 className=' title text-xl font-semibold my-1'>Terms of Use</h3>
        <div className={`${Darkmode?" border-gray-800":" border-black"} border rounded-lg p-2 overflow-scroll h-[60vh]`}>
            <p className='mb-3'>Ethos Reserve Privacy Policy</p>
            <p className='mb-3'>Updated 7/5/2023</p>
            <p className='mb-3'>OATH Foundation per its commitment to transparency and user autonomy has prepared this Privacy Policy for its users' review. This Privacy Policy outlines how your data is handled when you use Ethos Reserve ("the Application"). By using the Application, you agree to the terms set forth in this Privacy Policy.</p>
            <ol className=' pl-4 mb-3 list-decimal'>
                <li className='mb-1'>Data Collection: While public blockchain data is often used in the development and maintenance of the Application, private data including but not limited to IP addresses, browser information, device information, session duration, and pages visited; and personal identifiable information such as names, address, emails, phone numbers, and tax identification numbers are not collected by the Application. The provided list is not to be taken as exhaustive; however, OATH Foundation takes into custody zero private information of the users of the Application, and as such, there is currently no obligation to implement data privacy systems either internal to the OATH Foundation regarding the Application or inherent to the Application itself.</li>
                <li className='mb-1'>Third-Party Integrations: The Application may integrate with third-party services that may in some cases collect user data. While care has been taken to choose reputable third parties, it's important to note that they operate outside the liability of Oath Foundation and the Application and in the event of a security breach under a third-party integration, OATH Foundation may not be held responsible. At this time there are no third-party integrations in place.</li>
                <li className='mb-1'>Data Security Measures: The blockchain inherently protects user privacy. At this time, there is no requirement for KYC ("Know Your Customer") policies to use the Application. Until there is a need to do so, OATH Foundation and the Application will not require personal data collection to use the Application. However, once a user has decided to use features on the Application made possible by third-party integrations, any data that would be collected by the third-party would be subject to their own security policies.</li>
                <li className="mb-1">Updates to Privacy Policy: This Privacy Policy may be updated periodically to reflect any changes in our data handling practices or legal requirements. It is your responsibility to review this policy regularly. By continuing to use the Application after any updates, you agree to the revised terms.</li>
            </ol>
            <p className="my-4">Ethos Reserve Disclaimer</p>
            <ol className='pl-4 mb-3 list-decimal'>
                <li className="mb-1">Please read the entirety of this "Disclaimer" for Ethos Reserve, “the Protocol.” Nothing herein constitutes legal, financial, business or tax advice and you should consult your own legal, financial, tax or other professional advisor(s) before engaging in any activity in connection herewith. Neither the Byte Masons team, OATH Token Limited, or the OATH Foundation, any of the project team members who have worked on the OATH protocol or project to develop the OATH protocol in any way whatsoever, any distributor/vendor of OATH tokens, including without limitation OATH Token Limited and/or the OATH Foundation, nor any service provider shall be liable for any kind of direct or indirect damage or loss whatsoever which you may suffer in connection with accessing the website at ethos.finance or any other websites or materials published by the Byte Masons team, the OATH Foundation, and/or OATH Token Limited.</li>
                <li className="mb-1">Purpose: These terms and conditions govern the use of the Protocol, which is an experimental platform for decentralized financial transactions. The platform is provided on an “as is” and “as available” basis.</li>
                <li className="mb-1">Risks: Use of the Protocol involves numerous risks, including but not limited to the loss of digital assets, market volatility, and cybersecurity threats. Users are solely responsible for conducting their own research and assessment of these risks.</li>
                <li className="mb-1">No Warranty: The Protocol is provided without any representations or warranties of any kind, express or implied. The Byte Masons team, OATH Token Limited, and the OATH Foundation makes no representations or warranties in relation to the platform and its availability or reliability. Nothing on the website constitutes any offer by the Byte Masons team, the OATH Foundation, and/or OATH Token Limited team to sell any OATH tokens nor shall it or any part of it nor the fact of its presentation form the basis of, or be relied upon in connection with, any contract or investment decision. Nothing contained on the website is or may be relied upon as a promise, representation or undertaking as to the future performance of the Protocol. The agreement between any third party and you, in relation to any sale, purchase, or other distribution or transfer of OATH tokens, is to be governed only by the separate terms and conditions of such agreement.</li>
                <li className="mb-1">Documentation: The information set out on the website is for community discussion only and is not legally binding. No person is bound to enter into any contract or binding legal commitment in relation to the acquisition of OATH tokens, and no virtual currency or other form of payment is to be accepted on the basis of the website.</li>
                <li className="mb-1">Deemed Representations and Warranties:
                <ul className=' pl-4 list-disc'>
                    <li className="mb-1">In any decision to procure any OATH tokens, you shall not rely on any statement set out on the website or the associated social media channels thereof;</li>
                    <li className="mb-1">You will and shall at your own expense ensure compliance with all laws, regulatory requirements and restrictions applicable to you (as the case may be);</li>
                    <li className="mb-1">You acknowledge, understand and agree that OATH tokens may have no value, there is no guarantee or representation of value or liquidity for OATH tokens, and OATH tokens are not an investment product including for any speculative investment;</li>
                    <li className="mb-1">None of the Byte Masons team, the OATH Foundation, and/or OATH Token Limited team shall be responsible for or liable for the value of OATH tokens, the transferability and/or liquidity of OATH tokens and/or the availability of any market for OATH tokens through third parties or otherwise;</li>
                    <li className="mb-1">You nor any of your affiliates or direct or indirect beneficial owners, if applicable; (i) appears on the Specially Designated Nationals and Blocked Persons List of the Office of Foreign Assets Control of the United States Department of the Treasury (“OFAC”), the EU consolidated list of persons, groups and entities subject to financial sanctions, the UK Consolidated List of Financial Sanctions Targets, nor are they otherwise a party with which the OATH Foundation and/or OATH Token Limited team is prohibited to deal under the laws of the United States, the EU (or any of its Member States), or the UK; or (ii) is a person identified as a terrorist organization on any other relevant lists maintained by any governmental authority; and</li>
                    <li className="mb-1">You represent and warrant that, if applicable, you: (a) have conducted thorough due diligence with respect to all of your beneficial owners; (b) have established the identities of all direct and indirect beneficial owners and the source of each beneficial owners’ funds; and (c) will retain evidence of those identities, any source of funds and any due diligence.</li>
                </ul></li>
                <li className="mb-1">Limitation of Liability: The Byte Masons team, OATH Token Limited, or OATH Foundation teams do not and do not purport to make, and hereby disclaims, all representations, warranties or undertaking to any entity or person (including without limitation warranties as to the accuracy, completeness, timeliness or reliability of the contents of the website, or any other materials published by Byte Masons team, OATH Token Limited, or OATH Foundation). To the maximum extent permitted by law, the Byte Masons team, OATH Token Limited, or OATH Foundation shall not be liable for any indirect, special, incidental, consequential or other losses of any kind, in tort, contract or otherwise (including, without limitation, any liability arising from default or negligence on the part of any of them, or any loss of revenue, income or profits, and loss of use or data) arising from the use of the website, or any other materials published, or its contents (including without limitation any errors or omissions) or otherwise arising in connection with the same. The user assumes full responsibility and liability for any losses resulting from any intentional or unintentional misuse of the Protocol including, without limitation, the loss of the user’s private keys associated with any wallet used to hold OATH tokens, any loss resulting from designating a non-OATH token compliant wallet, depositing one type of digital asset to a wallet intended for another type of digital wallet, or any third party gaining access to the user’s wallet and misappropriating any OATH tokens or other digital assets. The Byte Masons team, OATH Token Limited, and/or the OATH Foundation assume no responsibility or liability in connection with any such misuse by the user or any third party or any loss of the user’s private keys associated with the user’s wallet.</li>
                <li className='mb-1'>Regulatory Disclosure: No regulatory authority has examined or approved, whether formally or informally, of any of the information set out on the website. No such action or assurance has been or will be taken under the laws, regulatory requirements or rules of any jurisdiction. The publication, distribution or dissemination of the website does not imply that the applicable laws, regulatory requirements or rules have been complied with.</li>
                <li className="mb-1">Changes to Terms: The Byte Masons team, the OATH Foundation, and/or OATH Token Limited reserves the right to modify these terms and conditions at any time without prior notice. Continued use of the Protocol following such changes constitutes acceptance of the modified terms. There are no obligations to update the website or to provide recipients with access to any information beyond what is provided herein.</li>
                <li className="mb-1">Governing Law: These terms and conditions shall be governed by and construed in accordance with the laws of the Cayman Islands.</li>
                <li className="mb-1">Dispute Resolution: Any dispute arising out of or in connection with these terms and conditions, the Protocol, or any related transactions shall be subject to the exclusive jurisdiction of the Cayman Islands courts.</li>
                <li className="mb-1">Intellectual Property: The Protocol and its content are protected by intellectual property laws, and all rights, title, and interest in and to the platform and its content shall remain with the OATH Foundation team.</li>
                <li className="mb-1">
                Forward-Looking Statements: All statements contained herein, statements made in press releases or in any place accessible by the public and oral statements that may be made by the Byte Masons team, OATH Token Limited, and/or OATH Foundation, may constitute forward-looking statements (including statements regarding intent, belief or current expectations with respect to market conditions, business strategy and plans, financial condition, specific provisions and risk management practices). You are cautioned not to place undue reliance on these forward-looking statements given that these statements involve known and unknown risks, uncertainties and other factors that may cause the actual future results to be materially different from that described by such forward-looking statements, and no independent third party has reviewed the reasonableness of any such statements or assumptions.
                </li>
                <li className="mb-1">No Distribution: No part of the website is to be copied, reproduced, distributed or disseminated in any way without the prior written consent of the Byte Masons team, OATH Token Limited, and/or OATH Foundation.</li>
            </ol>

        </div>
        <div onClick={()=> {setshowTerm(false)}} className=' cursor-pointer mt-2 p-2 rounded shadow'>Okay</div>
      </div>
    </div>
  )
}

export default DashboardTerms
